#       $OpenBSD: pf.conf,v 1.55 2017/12/03 20:40:04 sthen Exp $
#
# See pf.conf(5) and /etc/examples/pf.conf

#set skip on lo

#block return   # block stateless traffic
#pass           # establish keep-state

# By default, do not permit remote connections to X11
#block return in on ! lo0 proto tcp to port 6000:6010

# Port build user does not need network
#block return out log proto {tcp udp} user _pbuild
wired = "em1"
dmz = "em2"
#wifi  = "athn0"

table <lan_net> { 192.168.1.0/24 }
table <dmz_net> { 172.16.1.0/24 } 
table <martians> { 0.0.0.0/8 10.0.0.0/8 127.0.0.0/8 169.254.0.0/16     \
                   172.16.0.0/12 192.0.0.0/24 192.0.2.0/24 224.0.0.0/3 \
                   192.168.0.0/16 198.18.0.0/15 198.51.100.0/24        \
                   203.0.113.0/24 ::/128 ::/96 ::1/128 ::ffff:0:0/96 100::/64   \
                   2001:10::/28 2001:2::/48 2001:db8::/32        \
                   3ffe::/16 fec0::/10 fc00::/7 }

set block-policy drop
set loginterface egress
set skip on lo0
match in all scrub (no-df random-id max-mss 1440)
match out on egress inet from !(egress:network) to any nat-to (egress:0)
antispoof quick for { egress $wired $dmz }
block in quick on egress from <martians> to any
block return out quick on egress from any to <martians>
block all

# pfbadhost 
# configure with https://www.geoghegan.ca/pfbadhost.html

table <pfbadhost> persist file "/etc/pf-badhost.txt"
block in quick on egress from <pfbadhost>
block out quick on egress to <pfbadhost>

pass out quick keep state
pass in on { $wired $dmz } # do not include dmz
# ipv6 rules
pass in on egress inet6 proto icmp6 all \
  icmp6-type { routeradv neighbrsol neighbradv }
pass in on egress inet6 proto udp \
  from fe80::/10 port dhcpv6-server \
  to fe80::/10 port dhcpv6-client \
  no state
pass in on egress inet6 proto icmp6 all icmp6-type echoreq 

# ssh
block in quick on egress proto tcp from $dmz to any port ssh 
pass in on egress proto tcp from any to any port ssh

# DMZ options
block in quick on $wired from <dmz_net> to $wired

# DMZ port forwards
server1 = 10.0.0.2

pass in on egress inet proto tcp from any to any port 43029 rdr-to $server1 port 22 #server1 ssh
pass in on $wired proto tcp from <lan_net> to egress port 43029 rdr-to $server1 port 22
pass out on $wired proto tcp to $server1 port 43029 received-on $wired nat-to $wired port 22

pass in on egress inet proto tcp from any to any port {80 443} rdr-to $server1 #server1 http(s)
pass in on $wired proto tcp from <lan_net> to egress port {80 443} rdr-to $server1
pass out on $wired proto tcp to $server1 port {80 443} received-on $wired nat-to $wired

pass in on egress inet proto tcp from any to any port 4242 rdr-to $server1 #server1 quassel
pass in on $wired proto tcp from <lan_net> to egress port 4242 rdr-to $server1
pass out on $wired proto tcp to $server1 port 4242 received-on $wired nat-to $wired


# OpenVPN
vpn_network="10.2.0.0/24"
ovpn_if="tun0"
set skip on tun 
pass out on egress proto udp from self to any port 1194 # Outgoing traffic
pass in on egress proto udp from any to self port 1194 # UDP in
pass in on egress proto tcp from any to self port 1194 # TCP in 

match out inet from $vpn_network to any nat-to egress static-port source-hash
pass in quick on tun0
