# /etc/relayd.conf
# server1.local relay
table <httpd> { 127.0.0.1 }
table <webapp> { 192.168.2.52 }


http protocol "httpfilter" {
    # Performance enhancement, see "Relayd and Httpd Mastery" book
    tcp {nodelay, sack, backlog 128}

    # Return HTTP/HTML error pages to the client
    return error

    # Pass headers to webserver
    match header set "X-Client-IP" \
        value "$REMOTE_ADDR:$REMOTE_PORT"
    match header set "X-Forwarded-For" \
        value "$REMOTE_ADDR"
    match header set "X-Forwarded-By" \
        value "$SERVER_ADDR:$SERVER_PORT"

    # NOTE it is important to forward to a table
    match request path "/myapp/*" forward to <webapp>	
    
    # cert renewal directory
    #pass request quick path "/.well-known/acme-challenge/*" forward to 127.0.0.1 port 4220
    
    # pass only specific domains 
    pass request quick header "Host" value "server1.local" forward to <webapp>
    pass request quick header "Host" value "router1.local" forward to <httpd>
    block
}

http protocol "httpsfilter" {
    # Performance enhancement, see "Relayd and Httpd Mastery" book
    tcp {nodelay, sack, backlog 128}

    # Return HTTP/HTML error pages to the client
    return error

    # Pass headers to webserver
    match header set "X-Client-IP" \
        value "$REMOTE_ADDR:$REMOTE_PORT"
    match header set "X-Forwarded-For" \
        value "$REMOTE_ADDR"
    match header set "X-Forwarded-By" \
        value "$SERVER_ADDR:$SERVER_PORT"

    # NOTE it is important to forward to a table
    match request path "/myapp/*" forward to <webapp>
    
    # pass only specific domains
    pass request quick header "Host" value "server1.local" forward to <webapp>
    pass request quick header "Host" value "router1.local" forward to <httpd>
    block
}

relay "reverseproxy" {
    # Listen on localhost, accept diverted connections from pf(4)
    # Or change this to an external ip
    listen on 0.0.0.0 port 80

    protocol "httpfilter"
    # WARN <webhost> on port 80 is required to come first
    forward to <httpd> port 4220
    forward to <webapp> port 80
}

relay "server1.local" {
    listen on 0.0.0.0 port 443 tls
    protocol httpsfilter
    forward to <httpd> port 4220
    forward with tls to <webapp> port 443
}
