#
# Administers OpenBSD routers only
#

# list of openbsd routers
[openbsd]
localhost

[openbsd:vars]
ansible_connection=ssh
ansible_become=true
# doas used in openbsd
ansible_become_method=doas
ansible_interpreter_python_fallback=['/usr/local/bin/python3']
#ansible_perl_interpreter=/usr/bin/perl
